### ISSUE TITLE
Error during build with libwebsockets v4.0.21

### ISSUE THREAD

**Issue by lorenzo-arena** [mesonbuild/wrapdb#595]
I'm trying to build a project with libwebsockets using the latest v4.0.21 wrap; I added the dependency in my *meson.build* file using

```
libwebsockets_proj = subproject('libwebsockets', default_options: ['warning_level=0', 'werror=false'])
libwebsockets_dep = libwebsockets_proj.get_variable('libwebsockets_dep')
```

However, when trying to build I get this error:

```
../subprojects/libwebsockets-v4.0.21/include/libwebsockets.h:42:10: fatal error: lws_config.h: No such file or directory
   42 | #include "lws_config.h"
      |          ^~~~~~~~~~~~~~
compilation terminated.
```

I can see that the header file is being correctly generated during the build:

```
~ find . -iname "lws_config*"
./subprojects/libwebsockets-v4.0.21/lws_config_private.h
./subprojects/libwebsockets-v4.0.21/lws_config.h
```

**Comment by neheb** [comment]
Needs to be added in declare_dependency.

**Comment by neheb** [comment]
https://github.com/mesonbuild/wrapdb/blob/master/subprojects/packagefiles/libwebsockets/meson.build#L347 needs '.' included.
